### ISSUE TITLE
Obtener lista de Biller activos en Arcus

### ISSUE THREAD

**Issue by felipaoo** [cuenca-mx/arcus-python#37]
Crear métodos para el cliente de Arcus que permitan obtener lista de biller_id activos.

**Comment by matin** [comment]
similar to this: https://github.com/cuenca-mx/regalii-certifier/blob/master/regalii_certifier/etl_billers.py

**Comment by matin** [comment]
What about implementing `client.billers.list()`? That could return a generator that could be used for any script that'd want to either save the results to a db or csv

**Comment by matin** [comment]
should be able to filter on relevant fields like `country` and `currency`. (Don't hardcode the fields)

```
 {'id': 13599,
  'name': 'TAEIUSACELL',
  'country': 'MX',
  'currency': 'MXN',
  'biller_type': 'MXCell',
  'bill_type': 'phone_number',
  'available_topup_amounts': ['10.00',
   '20.00',
   '30.00',
   '50.00',
   '100.00',
   '150.00',
   '200.00',
   '300.00',
   '500.00',
   '600.00',
   '800.00',
   '900.00',
   '1000.00',
   '1200.00'],
  'topup_fxrate': 1.0,
  'mask': '(999) 999-9999',
  'topup_commission': 7.5,
  'account_number_digits': '10'},
```
