### ISSUE TITLE
cache dependencies to speed up TravisCI build process

### ISSUE THREAD

**Issue by matin** [cuenca-mx/arcus-python#41]
https://docs.travis-ci.com/user/caching/#pip-cache

**Comment by matin** [comment]
I don't think this is actually happening—given how long it takes travis to build.

**Comment by reqm87** [comment]
@matin I think this task is done. I checked the **.travis.yml** file and it has the configuration for pip to cache dependencies to speed up TravisCI build process.

https://github.com/cuenca-mx/arcus-python/blob/master/.travis.yml#L6

**Comment by matin** [comment]
ok
